version: 2
updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "16:00"
      timezone: "America/Montreal"
    assignees:
      - "montransit"
    groups:
      gh-actions:
        patterns:
          - "actions/*"
    open-pull-requests-limit: 7
